name: run-tests
run-name: run tests
on: [push]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: install bash
        run: sudo apt install bash

      - name: run tests
        run: cd tests/ && ./run_tests.sh
